### ISSUE TITLE
Library is thinking that there might be a tag in this defaultMessage

### ISSUE THREAD

**Issue by KiprasJ** [akameco/extract-react-intl-messages#81]
- version: 4.1.1
- `node` version: 12.14.1
- `npm` (or `yarn`) version: 6.14.5

I presume that the library is thinking that there might be a tag in this defaultMessage. How can I fix this?

`SyntaxError: D:\Dev\unispektras-service-app-fe\src\components\Login\Login.tsx: [React Intl] Message failed to parse. See: https://formatjs.io/docs/icu-syntax
SyntaxError: Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.
  38 |  test: {
  39 |          id: 'test.test',
> 40 |          defaultMessage: '< 10'
     |                          ^^^^^^
  41 |  }
  42 | });
  43 | 
    at File.buildCodeFrameError (D:\Dev\unispektras-service-app-fe\node_modules\@babel\core\lib\transformation\file\file.js:248:12)
    at NodePath.buildCodeFrameError (D:\Dev\unispektras-service-app-fe\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\index.js:144:21)
    at getICUMessageValue (D:\Dev\unispektras-service-app-fe\node_modules\babel-plugin-react-intl\dist\index.js:66:27)
    at evaluateMessageDescriptor (D:\Dev\unispektras-service-app-fe\node_modules\babel-plugin-react-intl\dist\index.js:113:26)
    at processMessageObject (D:\Dev\unispektras-service-app-fe\node_modules\babel-plugin-react-intl\dist\index.js:388:38)
    at Array.forEach (<anonymous>)
    at PluginPass.CallExpression (D:\Dev\unispektras-service-app-fe\node_modules\babel-plugin-react-intl\dist\index.js:415:38)
    at newFn (D:\Dev\unispektras-service-app-fe\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:179:21)
    at NodePath._call (D:\Dev\unispektras-service-app-fe\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (D:\Dev\unispektras-service-app-fe\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:42:17)
`

**Comment by mmmols** [comment]
`<FormattedMessage id="test.test" defaultMessage="{lessThan} 10" values={{lessThan: "<"}}`
